# Site settings
title: Matheus VillalÃ³n, Frontend Developer - Online Portfolio
email: olavillalon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://olavillalon.github.io" # the base hostname & protocol for your site

favicon: images/favicon.png

# Build settings
markdown: kramdown